{% set name = "napari-organoid-counter" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-organoid-counter-{{ version }}.tar.gz
  sha256: 6a596bbbcf2653334ffbdee8bd0303b39549d7223d194a774ee3292db1b3e31a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.10
    - setuptools-scm
  run:
    - napari >=0.4.15
    - napari-aicsimageio >=0.6.1
    - python >=3.8,<3.10

test:
  imports:
    - napari_organoid_counter
  commands:
    - pip list
    # - pip check  # Fails due to aicsimageio deps and fixed constraintes that were relaxed
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-organoid-counter
  summary: A plugin to automatically count lung organoids
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter

extra:
  recipe-maintainers:
    - christinab12
    - goanpeca
    - jaimergp
