{% set name = "napari-organoid-counter" %}
{% set version = "0.2.9" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-organoid-counter-{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >={{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy ==1.26.4
    - napari ==0.7.0
    - bioio ==3.3.0
    - bioio-ome-tiff ==1.4.0
    - bioio-tifffile ==1.3.0
    - bioio-imageio ==1.3.0
    - bioio-czi ==2.6.0
    - bioio-nd2 ==1.6.2
    - bioio-lif ==1.4.0
    - bioio-dv ==1.2.0
    - pytorch <=2.5.1
    - torchvision ==0.20.1
    - opencv
    - lxml_html_clean ==0.4.4
    - onnxruntime ==1.23.0  
    - qtpy

test:
  imports:
    - napari_organoid_counter
  commands:
    - pip list
    # - pip check  # Fails due to aicsimageio deps and fixed constraints that were relaxed
  requires:
    - python {{ python_min }}
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-organoid-counter
  summary: A plugin to automatically count lung organoids
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter

extra:
  recipe-maintainers:
    - francesco-campi
    - christinab12
    - goanpeca
    - jaimergp
